CREATE TABLE `SiteSettings` (
    `id` INTEGER NOT NULL,
    `websiteTitle` VARCHAR(191) NOT NULL,
    `websiteDescription` TEXT NOT NULL,
    `seoTitle` VARCHAR(191) NOT NULL,
    `seoDescription` TEXT NOT NULL,
    `seoKeywords` TEXT NOT NULL,
    `seoImage` VARCHAR(191) NOT NULL,
    `websiteIcon` VARCHAR(191) NOT NULL,
    `heroHeaderText` TEXT NOT NULL,
    `heroDescription` TEXT NOT NULL,
    `heroImage` VARCHAR(191) NOT NULL,
    `contactEmail` VARCHAR(191) NOT NULL,
    `mobileNumber` VARCHAR(191) NOT NULL,
    `footerText` TEXT NOT NULL,
    `canonicalUrl` VARCHAR(191) NOT NULL,
    `googleSiteVerification` VARCHAR(191) NOT NULL,
    `googleAnalyticsId` VARCHAR(191) NOT NULL,
    `googleTagManagerId` VARCHAR(191) NOT NULL,
    `robotsIndexingEnabled` BOOLEAN NOT NULL DEFAULT true,
    `robotsFollowEnabled` BOOLEAN NOT NULL DEFAULT true,
    `smtpHost` VARCHAR(191) NOT NULL,
    `smtpPort` INTEGER NOT NULL DEFAULT 587,
    `smtpUser` VARCHAR(191) NOT NULL,
    `smtpPass` TEXT NOT NULL,
    `smtpSecure` BOOLEAN NOT NULL DEFAULT false,
    `smtpFromEmail` VARCHAR(191) NOT NULL,
    `smtpFromName` VARCHAR(191) NOT NULL,
    `smtpReplyToEmail` VARCHAR(191) NOT NULL,
    `smtpToEmail` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
);
