services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    environment:
      NEXT_PUBLIC_APP_URL: http://localhost:3005
      NEXT_PUBLIC_BACKEND_URL: http://localhost:5005
      BACKEND_URL: http://backend:5000
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    ports:
      - "3005:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    environment:
      PORT: 5000
      FRONTEND_URL: http://localhost:3005
      BACKEND_URL: http://localhost:5005
    env_file:
      - ./backend/.env
    ports:
      - "5005:5000"
