ALTER TABLE `ContactMessage`
    ADD COLUMN `subject` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `photo` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `file` VARCHAR(191) NOT NULL DEFAULT '';
