ALTER TABLE `Project`
    ADD COLUMN `image` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `views` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `impressionCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `buttons` JSON NOT NULL DEFAULT (JSON_ARRAY());
