ALTER TABLE `Testimonial`
    MODIFY `id` INTEGER NOT NULL AUTO_INCREMENT,
    ADD COLUMN `position` VARCHAR(191) NOT NULL DEFAULT '' AFTER `company`,
    ADD COLUMN `stars` INTEGER NOT NULL DEFAULT 5 AFTER `position`;
